#include "xkey_code.h"

/*WinxKeyCode keysym_to_key_code(KeySym keysym) {
  switch (keysym) {
  case 65307: return WinxKeyCodeEscape;
  case 65289: return WinxKeyCodeTab;
  case 65505: return WinxKeyCodeLeftShift;
  case 65506: return WinxKeyCodeRightShift;
  case 65507: return WinxKeyCodeLeftControl;
  case 65508: return WinxKeyCodeRightControl;
  case 65511: return WinxKeyCodeLeftAlt;
  case 65406: return WinxKeyCodeRightAlt;
  case 65515: return WinxKeyCodeLeftSuper;
  case 65516: return WinxKeyCodeRightSuper;
  case 65383: return WinxKeyCodeMenu;
  case 65407: return WinxKeyCodeNumLock;
  case 65509: return WinxKeyCodeCapsLock;
  case 65377: return WinxKeyCodePrintScreen;
  case 65300: return WinxKeyCodeScrollLock;
  case 65299: return WinxKeyCodePause;
  case 65535: return WinxKeyCodeDelete;
  case 65288: return WinxKeyCodeBackspace;
  case 65293: return WinxKeyCodeEnter;
  case 65360: return WinxKeyCodeHome;
  case 65367: return WinxKeyCodeEnd;
  case 65365: return WinxKeyCodePageUp;
  case 65366: return WinxKeyCodePageDown;
  case 65379: return WinxKeyCodeInsert;
  case 65361: return WinxKeyCodeLeft;
  case 65363: return WinxKeyCodeRight;
  case 65364: return WinxKeyCodeDown;
  case 65362: return WinxKeyCodeUp;
  case 65470: return WinxKeyCodeF1;
  case 65471: return WinxKeyCodeF2;
  case 65472: return WinxKeyCodeF3;
  case 65473: return WinxKeyCodeF4;
  case 65474: return WinxKeyCodeF5;
  case 65475: return WinxKeyCodeF6;
  case 65476: return WinxKeyCodeF7;
  case 65477: return WinxKeyCodeF8;
  case 65478: return WinxKeyCodeF9;
  case 65479: return WinxKeyCodeF10;
  case 65480: return WinxKeyCodeF11;
  case 65481: return WinxKeyCodeF12;
  case 65482: return WinxKeyCodeF13;
  case 65483: return WinxKeyCodeF14;
  case 65484: return WinxKeyCodeF15;
  case 65485: return WinxKeyCodeF16;
  case 65486: return WinxKeyCodeF17;
  case 65487: return WinxKeyCodeF18;
  case 65488: return WinxKeyCodeF19;
  case 65489: return WinxKeyCodeF20;
  case 65490: return WinxKeyCodeF21;
  case 65491: return WinxKeyCodeF22;
  case 65492: return WinxKeyCodeF23;
  case 65493: return WinxKeyCodeF24;
  case 65494: return WinxKeyCodeF25;
  case 65455: return WinxKeyCodeKpDivide;
  case 65450: return WinxKeyCodeKpMultiply;
  case 65453: return WinxKeyCodeKpSubtract;
  case 65451: return WinxKeyCodeKpAdd;
  case 65438: return WinxKeyCodeKp0;
  case 65436: return WinxKeyCodeKp1;
  case 65433: return WinxKeyCodeKp2;
  case 65435: return WinxKeyCodeKp3;
  case 65430: return WinxKeyCodeKp4;
  case 65437: return WinxKeyCodeKp5;
  case 65432: return WinxKeyCodeKp6;
  case 65429: return WinxKeyCodeKp7;
  case 65431: return WinxKeyCodeKp8;
  case 65434: return WinxKeyCodeKp9;
  case 65439: return WinxKeyCodeKpDecimal;
  case 65469: return WinxKeyCodeKpEqual;
  case 65421: return WinxKeyCodeKpEnter;
  case 97:    case: return WinxKeyCodereturn WinxKeyCodeA;
  case 98:    case: return WinxKeyCodereturn WinxKeyCodeB;
  case 99:    case: return WinxKeyCodereturn WinxKeyCodeC;
  case 100:   return WinxKeyCodeD;
  case 101:   return WinxKeyCodeE;
  case 102:   return WinxKeyCodeF;
  case 103:   return WinxKeyCodeG;
  case 104:   return WinxKeyCodeH;
  case 105:   return WinxKeyCodeI;
  case 106:   return WinxKeyCodeJ;
  case 107:   return WinxKeyCodeK;
  case 108:   return WinxKeyCodeL;
  case 109:   return WinxKeyCodeM;
  case 110:   return WinxKeyCodeN;
  case 111:   return WinxKeyCodeO;
  case 112:   return WinxKeyCodeP;
  case 113:   return WinxKeyCodeQ;
  case 114:   return WinxKeyCodeR;
  case 115:   return WinxKeyCodeS;
  case 116:   return WinxKeyCodeT;
  case 117:   return WinxKeyCodeU;
  case 118:   return WinxKeyCodeV;
  case 119:   return WinxKeyCodeW;
  case 120:   return WinxKeyCodeX;
  case 121:   return WinxKeyCodeY;
  case 122:   return WinxKeyCodeZ;
  case 49:    case: return WinxKeyCodereturn WinxKeyCode1;
  case 50:    case: return WinxKeyCodereturn WinxKeyCode2;
  case 51:    case: return WinxKeyCodereturn WinxKeyCode3;
  case 52:    case: return WinxKeyCodereturn WinxKeyCode4;
  case 53:    case: return WinxKeyCodereturn WinxKeyCode5;
  case 54:    case: return WinxKeyCodereturn WinxKeyCode6;
  case 55:    case: return WinxKeyCodereturn WinxKeyCode7;
  case 56:    case: return WinxKeyCodereturn WinxKeyCode8;
  case 57:    case: return WinxKeyCodereturn WinxKeyCode9;
  case 48:    case: return WinxKeyCodereturn WinxKeyCode0;
  case 32:    case: return WinxKeyCodereturn WinxKeyCodeSpace;
  case 45:    case: return WinxKeyCodereturn WinxKeyCodeMinus;
  case 61:    case: return WinxKeyCodereturn WinxKeyCodeEqual;
  case 91:    case: return WinxKeyCodereturn WinxKeyCodeLeftBracket;
  case 93:    case: return WinxKeyCodereturn WinxKeyCodeRightBracket;
  case 92:    case: return WinxKeyCodereturn WinxKeyCodeBackslash;
  case 59:    case: return WinxKeyCodereturn WinxKeyCodeSemicolon;
  case 39:    case: return WinxKeyCodereturn WinxKeyCodeApostrophe;
  case 44:    case: return WinxKeyCodereturn WinxKeyCodeComma;
  case 46:    case: return WinxKeyCodereturn WinxKeyCodePeriod;
  case 47:    case: return WinxKeyCodereturn WinxKeyCodeSlash;
  default:    case: return WinxKeyCodereturn WinxKeyCodeA;
  }
}*/

WinxKeyCode keysym_to_key_code(KeySym keysym) {
  switch (keysym) {
    case 0x0020: return WinxKeyCodeSpace;
    case 0x0027: return WinxKeyCodeApostrophe;
    case 0x002c: return WinxKeyCodeComma;
    case 0x002d: return WinxKeyCodeMinus;
    case 0x002e: return WinxKeyCodePeriod;
    case 0x002f: return WinxKeyCodeSlash;
    case 0x0030: return WinxKeyCode0;
    case 0x0031: return WinxKeyCode1;
    case 0x0032: return WinxKeyCode2;
    case 0x0033: return WinxKeyCode3;
    case 0x0034: return WinxKeyCode4;
    case 0x0035: return WinxKeyCode5;
    case 0x0036: return WinxKeyCode6;
    case 0x0037: return WinxKeyCode7;
    case 0x0038: return WinxKeyCode8;
    case 0x0039: return WinxKeyCode9;
    case 0x003b: return WinxKeyCodeSemicolon;
    case 0x003d: return WinxKeyCodeEqual;
    case 0x0041: return WinxKeyCodeA;
    case 0x0042: return WinxKeyCodeB;
    case 0x0043: return WinxKeyCodeC;
    case 0x0044: return WinxKeyCodeD;
    case 0x0045: return WinxKeyCodeE;
    case 0x0046: return WinxKeyCodeF;
    case 0x0047: return WinxKeyCodeG;
    case 0x0048: return WinxKeyCodeH;
    case 0x0049: return WinxKeyCodeI;
    case 0x004a: return WinxKeyCodeJ;
    case 0x004b: return WinxKeyCodeK;
    case 0x004c: return WinxKeyCodeL;
    case 0x004d: return WinxKeyCodeM;
    case 0x004e: return WinxKeyCodeN;
    case 0x004f: return WinxKeyCodeO;
    case 0x0050: return WinxKeyCodeP;
    case 0x0051: return WinxKeyCodeQ;
    case 0x0052: return WinxKeyCodeR;
    case 0x0053: return WinxKeyCodeS;
    case 0x0054: return WinxKeyCodeT;
    case 0x0055: return WinxKeyCodeU;
    case 0x0056: return WinxKeyCodeV;
    case 0x0057: return WinxKeyCodeW;
    case 0x0058: return WinxKeyCodeX;
    case 0x0059: return WinxKeyCodeY;
    case 0x005a: return WinxKeyCodeZ;
    case 0x005b: return WinxKeyCodeLeftBracket;
    case 0x005c: return WinxKeyCodeBackslash;
    case 0x005d: return WinxKeyCodeRightBracket;
    case 0x0ff1b: return WinxKeyCodeEscape;
    case 0xff0d: return WinxKeyCodeEnter;
    case 0xff09: return WinxKeyCodeTab;
    case 0xff08: return WinxKeyCodeBackspace;
    case 0xff63: return WinxKeyCodeInsert;
    case 0xffff: return WinxKeyCodeDelete;
    case 0xff53: return WinxKeyCodeRight;
    case 0xff51: return WinxKeyCodeLeft;
    case 0xff54: return WinxKeyCodeDown;
    case 0xff52: return WinxKeyCodeUp;
    case 0xff55: return WinxKeyCodePageUp;
    case 0xff56: return WinxKeyCodePageDown;
    case 0xff50: return WinxKeyCodeHome;
    case 0xff57: return WinxKeyCodeEnd;
    case 0xffe5: return WinxKeyCodeCapsLock;
    case 0xff14: return WinxKeyCodeScrollLock;
    case 0xff7f: return WinxKeyCodeNumLock;
    case 0xfd1d: return WinxKeyCodePrintScreen;
    case 0xff13: return WinxKeyCodePause;
    case 0xffbe: return WinxKeyCodeF1;
    case 0xffbf: return WinxKeyCodeF2;
    case 0xffc0: return WinxKeyCodeF3;
    case 0xffc1: return WinxKeyCodeF4;
    case 0xffc2: return WinxKeyCodeF5;
    case 0xffc3: return WinxKeyCodeF6;
    case 0xffc4: return WinxKeyCodeF7;
    case 0xffc5: return WinxKeyCodeF8;
    case 0xffc6: return WinxKeyCodeF9;
    case 0xffc7: return WinxKeyCodeF10;
    case 0xffc8: return WinxKeyCodeF11;
    case 0xffc9: return WinxKeyCodeF12;
    case 0xffca: return WinxKeyCodeF13;
    case 0xffcb: return WinxKeyCodeF14;
    case 0xffcc: return WinxKeyCodeF15;
    case 0xffcd: return WinxKeyCodeF16;
    case 0xffce: return WinxKeyCodeF17;
    case 0xffcf: return WinxKeyCodeF18;
    case 0xffd0: return WinxKeyCodeF19;
    case 0xffd1: return WinxKeyCodeF20;
    case 0xffd2: return WinxKeyCodeF21;
    case 0xffd3: return WinxKeyCodeF22;
    case 0xffd4: return WinxKeyCodeF23;
    case 0xffd5: return WinxKeyCodeF24;
    case 0xffd8: return WinxKeyCodeF25;
    case 0xffb0: return WinxKeyCodeKp0;
    case 0xffb1: return WinxKeyCodeKp1;
    case 0xffb2: return WinxKeyCodeKp2;
    case 0xffb3: return WinxKeyCodeKp3;
    case 0xffb4: return WinxKeyCodeKp4;
    case 0xffb5: return WinxKeyCodeKp5;
    case 0xffb6: return WinxKeyCodeKp6;
    case 0xffb7: return WinxKeyCodeKp7;
    case 0xffb8: return WinxKeyCodeKp8;
    case 0xffb9: return WinxKeyCodeKp9;
    case 0xffae: return WinxKeyCodeKpDecimal;
    case 0xffaf: return WinxKeyCodeKpDivide;
    case 0xffaa: return WinxKeyCodeKpMultiply;
    case 0xffad: return WinxKeyCodeKpSubtract;
    case 0xffab: return WinxKeyCodeKpAdd;
    case 0xff8d: return WinxKeyCodeKpEnter;
    case 0xffbd: return WinxKeyCodeKpEqual;
    case 0xffe1: return WinxKeyCodeLeftShift;
    case 0xffe3: return WinxKeyCodeLeftControl;
    case 0xffe9: return WinxKeyCodeLeftAlt;
    case 0xffeb: return WinxKeyCodeLeftSuper;
    case 0xffe2: return WinxKeyCodeRightShift;
    case 0xffe4: return WinxKeyCodeRightControl;
    case 0xffea: return WinxKeyCodeRightAlt;
    case 0xffec: return WinxKeyCodeRightSuper;
    case 0xff67: return WinxKeyCodeMenu;
    default:     return 0;
  }
}
