#include <windows.h>

#include "wkey_code.h"

WinxKeyCode virtual_key_to_key_code(WPARAM virtual_key) {
  switch (virtual_key) {
  case VK_SPACE:      return WinxKeyCodeSpace;
  case VK_OEM_7:      return WinxKeyCodeApostrophe;
  case VK_OEM_COMMA:  return WinxKeyCodeComma;
  case VK_OEM_MINUS:  return WinxKeyCodeMinus;
  case VK_OEM_PERIOD: return WinxKeyCodePeriod;
  case VK_OEM_2:      return WinxKeyCodeSlash;
  case 0x30:          return WinxKeyCode0;
  case 0x31:          return WinxKeyCode1;
  case 0x32:          return WinxKeyCode2;
  case 0x33:          return WinxKeyCode3;
  case 0x34:          return WinxKeyCode4;
  case 0x35:          return WinxKeyCode5;
  case 0x36:          return WinxKeyCode6;
  case 0x37:          return WinxKeyCode7;
  case 0x38:          return WinxKeyCode8;
  case 0x39:          return WinxKeyCode9;
  case VK_OEM_1:      return WinxKeyCodeSemicolon;
  case VK_OEM_PLUS:   return WinxKeyCodeEqual;
  case 0x41:          return WinxKeyCodeA;
  case 0x42:          return WinxKeyCodeB;
  case 0x43:          return WinxKeyCodeC;
  case 0x44:          return WinxKeyCodeD;
  case 0x45:          return WinxKeyCodeE;
  case 0x46:          return WinxKeyCodeF;
  case 0x47:          return WinxKeyCodeG;
  case 0x48:          return WinxKeyCodeH;
  case 0x49:          return WinxKeyCodeI;
  case 0x4a:          return WinxKeyCodeJ;
  case 0x4b:          return WinxKeyCodeK;
  case 0x4c:          return WinxKeyCodeL;
  case 0x4d:          return WinxKeyCodeM;
  case 0x4e:          return WinxKeyCodeN;
  case 0x4f:          return WinxKeyCodeO;
  case 0x50:          return WinxKeyCodeP;
  case 0x51:          return WinxKeyCodeQ;
  case 0x52:          return WinxKeyCodeR;
  case 0x53:          return WinxKeyCodeS;
  case 0x54:          return WinxKeyCodeT;
  case 0x55:          return WinxKeyCodeU;
  case 0x56:          return WinxKeyCodeV;
  case 0x57:          return WinxKeyCodeW;
  case 0x58:          return WinxKeyCodeX;
  case 0x59:          return WinxKeyCodeY;
  case 0x5a:          return WinxKeyCodeZ;
  case VK_OEM_4:      return WinxKeyCodeLeftBracket;
  case VK_OEM_5:      return WinxKeyCodeBackslash;
  case VK_OEM_6:      return WinxKeyCodeRightBracket;
  case VK_ESCAPE:     return WinxKeyCodeEscape;
  case VK_RETURN:     return WinxKeyCodeEnter;
  case VK_TAB:        return WinxKeyCodeTab;
  case VK_BACK:       return WinxKeyCodeBackspace;
  case VK_INSERT:     return WinxKeyCodeInsert;
  case VK_DELETE:     return WinxKeyCodeDelete;
  case VK_RIGHT:      return WinxKeyCodeRight;
  case VK_LEFT:       return WinxKeyCodeLeft;
  case VK_DOWN:       return WinxKeyCodeDown;
  case VK_UP:         return WinxKeyCodeUp;
  case VK_PRIOR:      return WinxKeyCodePageUp;
  case VK_NEXT:       return WinxKeyCodePageDown;
  case VK_HOME:       return WinxKeyCodeHome;
  case VK_END:        return WinxKeyCodeEnd;
  case VK_CAPITAL:    return WinxKeyCodeCapsLock;
  case VK_SCROLL:     return WinxKeyCodeScrollLock;
  case VK_NUMLOCK:    return WinxKeyCodeNumLock;
  case VK_SNAPSHOT:   return WinxKeyCodePrintScreen;
  case VK_PAUSE:      return WinxKeyCodePause;
  case VK_F1:         return WinxKeyCodeF1;
  case VK_F2:         return WinxKeyCodeF2;
  case VK_F3:         return WinxKeyCodeF3;
  case VK_F4:         return WinxKeyCodeF4;
  case VK_F5:         return WinxKeyCodeF5;
  case VK_F6:         return WinxKeyCodeF6;
  case VK_F7:         return WinxKeyCodeF7;
  case VK_F8:         return WinxKeyCodeF8;
  case VK_F9:         return WinxKeyCodeF9;
  case VK_F10:        return WinxKeyCodeF10;
  case VK_F11:        return WinxKeyCodeF11;
  case VK_F12:        return WinxKeyCodeF12;
  case VK_F13:        return WinxKeyCodeF13;
  case VK_F14:        return WinxKeyCodeF14;
  case VK_F15:        return WinxKeyCodeF15;
  case VK_F16:        return WinxKeyCodeF16;
  case VK_F17:        return WinxKeyCodeF17;
  case VK_F18:        return WinxKeyCodeF18;
  case VK_F19:        return WinxKeyCodeF19;
  case VK_F20:        return WinxKeyCodeF20;
  case VK_F21:        return WinxKeyCodeF21;
  case VK_F22:        return WinxKeyCodeF22;
  case VK_F23:        return WinxKeyCodeF23;
  case VK_F24:        return WinxKeyCodeF24;
  // WinxKeyCodeF25 not found
  case VK_NUMPAD0:    return WinxKeyCodeKp0;
  case VK_NUMPAD1:    return WinxKeyCodeKp1;
  case VK_NUMPAD2:    return WinxKeyCodeKp2;
  case VK_NUMPAD3:    return WinxKeyCodeKp3;
  case VK_NUMPAD4:    return WinxKeyCodeKp4;
  case VK_NUMPAD5:    return WinxKeyCodeKp5;
  case VK_NUMPAD6:    return WinxKeyCodeKp6;
  case VK_NUMPAD7:    return WinxKeyCodeKp7;
  case VK_NUMPAD8:    return WinxKeyCodeKp8;
  case VK_NUMPAD9:    return WinxKeyCodeKp9;
  case VK_DECIMAL:    return WinxKeyCodeKpDecimal;
  case VK_DIVIDE:     return WinxKeyCodeKpDivide;
  case VK_MULTIPLY:   return WinxKeyCodeKpMultiply;
  case VK_SUBTRACT:   return WinxKeyCodeKpSubtract;
  case VK_ADD:        return WinxKeyCodeKpAdd;
  // WinxKeyCodeKpEnter not found
  // WinxKeyCodeKpEqual not found
  case VK_LSHIFT:     return WinxKeyCodeLeftShift;
  case VK_LCONTROL:   return WinxKeyCodeLeftControl;
  case VK_LMENU:      return WinxKeyCodeLeftAlt;
  case VK_LWIN:       return WinxKeyCodeLeftSuper;
  case VK_RSHIFT:     return WinxKeyCodeRightShift;
  case VK_RCONTROL:   return WinxKeyCodeRightControl;
  case VK_RMENU:      return WinxKeyCodeRightAlt;
  case VK_RWIN:       return WinxKeyCodeRightSuper;
  // WinxKeyCodeMenu not found
  default:            return 0;
  }
}
